services:
  sonarqube_exporter:
    build: .
    depends_on:
    - sonarqube
    - prometheus
    ports:
      - 8198:8198
    environment:
      - SONARQUBE_SERVER=http://10.0.5.14:9000
      - SONARQUBE_TOKEN=squ_fb51c0dfa34ce606afe54e4eb54796a4bcc6ee53
    
    volumes:
      - ./:/src
    networks:
      sonarqube_network:
          ipv4_address: 10.0.5.11
  grafana:
    image: grafana/grafana:11.1.1
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000/api/health && echo 'ready'"]
      interval: 10s
      retries: 30
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      sonarqube_network:
          ipv4_address: 10.0.5.12
  prometheus:
    image: "prom/prometheus"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      #- "./config/prometheus.rules:/etc/prometheus/prometheus.rules.yml"
    ports:
      - "9090:9090"
    networks:
      sonarqube_network:
          ipv4_address: 10.0.5.13
  sonarqube:
    image: sonarqube:9.9.6-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://10.0.5.15:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
      - ./sonar/sysctl.conf:/etc/sysctl.conf
    networks:
      sonarqube_network:
          ipv4_address: 10.0.5.14
  sonar_db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      sonarqube_network:
          ipv4_address: 10.0.5.15
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
  grafana-data:
networks:
  sonarqube_network:
      name: 'sonarqube_network'
      ipam:
          config:
            - subnet: 10.0.5.0/24